# frozen_string_literal: true

puts "定期整備を作成中..."

def user_by(email) = User.find_by!(email: email)
def equip(site_name, equip_name) = Equipment.find_by!(site: Site.find_by!(name: site_name), name: equip_name)

kw_cdu = equip("川崎製油所", "常圧蒸留装置")
kw_rhds = equip("川崎製油所", "重油間接脱硫装置")
kw_fcc = equip("川崎製油所", "流動接触分解装置")
kw_boiler = equip("川崎製油所", "ボイラー設備")
kw_vdu = equip("川崎製油所", "減圧蒸留装置")
kw_crf = equip("川崎製油所", "接触改質装置")
kw_tank = equip("川崎製油所", "タンク設備")
ng_cdu = equip("根岸製油所", "常圧蒸留装置")
ng_hds = equip("根岸製油所", "軽油脱硫装置")
ng_boiler = equip("根岸製油所", "ボイラー設備")
sk_cdu = equip("堺製油所", "常圧蒸留装置")
sk_hds = equip("堺製油所", "軽油脱硫装置")
wk_cdu = equip("和歌山製油所", "常圧蒸留装置")
sd_lk = equip("仙台製油所", "潤滑油製造装置")

maintenances = {}

maintenances[:m1] = ScheduledMaintenance.create!(equipment: kw_cdu, title: "CDU 計器年次点検整備", description: "CDU全計器の年次点検整備。校正、部品交換、外観検査を実施。SDW期間中に実施。", scheduled_date: Date.new(2026, 4, 1), status: "planned")
maintenances[:m2] = ScheduledMaintenance.create!(equipment: kw_rhds, title: "RHDS 触媒交換時計器点検", description: "RHDS触媒交換に合わせた計器点検。高温高圧計器の校正・交換。", scheduled_date: Date.new(2026, 5, 15), status: "planned")
maintenances[:m3] = ScheduledMaintenance.create!(equipment: kw_boiler, title: "ボイラー 安全弁定期検査", description: "ボイラー安全弁の定期吹き出し試験および検査。法定検査対応。", scheduled_date: Date.new(2025, 11, 1), completed_date: Date.new(2025, 11, 3), status: "completed", used_materials: "安全弁スプリング × 2本、ガスケット（ノンアスベスト）× 4枚")
maintenances[:m4] = ScheduledMaintenance.create!(equipment: kw_fcc, title: "FCC 計器年次点検", description: "FCC装置計器の年次点検整備。", scheduled_date: Date.new(2026, 4, 15), status: "planned")
maintenances[:m5] = ScheduledMaintenance.create!(equipment: kw_vdu, title: "VDU 真空系計器点検", description: "VDU真空系の計器点検。真空ポンプ周りの計器校正。", scheduled_date: Date.new(2026, 3, 1), status: "planned")
maintenances[:m6] = ScheduledMaintenance.create!(equipment: kw_crf, title: "CRF 触媒交換時計器点検", description: "CRF触媒交換に合わせた計器一斉点検。", scheduled_date: Date.new(2026, 6, 1), status: "planned")
maintenances[:m7] = ScheduledMaintenance.create!(equipment: ng_cdu, title: "根岸CDU 年次点検", description: "根岸CDU全計器の年次点検。", scheduled_date: Date.new(2026, 5, 1), status: "planned")
maintenances[:m8] = ScheduledMaintenance.create!(equipment: ng_hds, title: "根岸HDS 定期整備", description: "根岸HDS計器定期整備。", scheduled_date: Date.new(2026, 4, 1), status: "planned")
maintenances[:m9] = ScheduledMaintenance.create!(equipment: sk_cdu, title: "堺CDU 年次点検", description: "堺CDU計器年次点検。", scheduled_date: Date.new(2026, 3, 15), status: "planned")
maintenances[:m10] = ScheduledMaintenance.create!(equipment: sk_hds, title: "堺HDS 定期整備", description: "堺HDS計器定期整備。", scheduled_date: Date.new(2026, 4, 15), status: "planned")
maintenances[:m11] = ScheduledMaintenance.create!(equipment: wk_cdu, title: "和歌山CDU 年次点検", description: "和歌山CDU計器年次点検。", scheduled_date: Date.new(2026, 5, 15), status: "planned")
maintenances[:m12] = ScheduledMaintenance.create!(equipment: sd_lk, title: "仙台LK 定期整備", description: "仙台LK計器定期整備。", scheduled_date: Date.new(2026, 3, 1), status: "planned")
maintenances[:m13] = ScheduledMaintenance.create!(equipment: kw_cdu, title: "CDU 前回年次点検", description: "前回の年次点検整備。完了済み。", scheduled_date: Date.new(2025, 4, 1), completed_date: Date.new(2025, 4, 5), status: "completed", used_materials: "差圧伝送器EJA110E × 1台、ガスケット × 10枚、ケーブル 30m")
maintenances[:m14] = ScheduledMaintenance.create!(equipment: ng_boiler, title: "根岸ボイラー 安全弁検査", description: "根岸ボイラー安全弁法定検査。", scheduled_date: Date.new(2025, 10, 1), completed_date: Date.new(2025, 10, 2), status: "completed")
maintenances[:m15] = ScheduledMaintenance.create!(equipment: kw_tank, title: "タンク計器点検", description: "タンクヤード全レベル計の定期点検。", scheduled_date: Date.new(2026, 2, 15), status: "planned")

# 整備担当
suzuki = user_by("suzuki@example.com")
sato = user_by("sato@example.com")
takahashi = user_by("takahashi@example.com")
yoshida = user_by("yoshida@example.com")
inoue = user_by("inoue@example.com")
fujita = user_by("fujita@example.com")
yamamoto = user_by("yamamoto@example.com")
nishimura = user_by("nishimura@example.com")
okada = user_by("okada@example.com")
yamashita = user_by("yamashita@example.com")
imai = user_by("imai@example.com")
ogata = user_by("ogata@example.com")
kimura = user_by("kimura@example.com")
tanabe = user_by("tanabe@example.com")
hayashi = user_by("hayashi@example.com")
wk_inst1 = user_by("doi@example.com")
sd_inst1 = user_by("chiba_t@example.com")
sd_inst2 = user_by("oikawa@example.com")

MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m1], user: suzuki, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m1], user: sato, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m1], user: takahashi, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m1], user: yoshida, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m1], user: inoue, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m2], user: suzuki, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m2], user: sato, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m3], user: fujita, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m3], user: yamamoto, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m4], user: takahashi, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m4], user: sato, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m5], user: nishimura, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m5], user: okada, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m6], user: inoue, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m7], user: yamashita, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m7], user: imai, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m7], user: ogata, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m8], user: imai, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m9], user: kimura, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m9], user: tanabe, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m10], user: hayashi, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m11], user: wk_inst1, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m12], user: sd_inst1, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m12], user: sd_inst2, role: "member")

# ============================================================
# 追加定期整備
# ============================================================
sk_crf2 = equip("堺製油所", "接触改質装置")
wk_fcc3 = equip("和歌山製油所", "流動接触分解装置")
sk_tank = equip("堺製油所", "タンク設備")
ng_tank = equip("根岸製油所", "タンク設備")
sd_tank = equip("仙台製油所", "タンク設備")
kw_rhds3 = equip("川崎製油所", "重油間接脱硫装置")

maintenances[:m16] = ScheduledMaintenance.create!(equipment: equip("川崎製油所", "常圧蒸留装置"), title: "CDU 調節弁定期整備（PV-201）", description: "CDU塔頂圧力制御弁PV-201の本格整備。グランドパッキン・弁体シール全交換。SDW期間中に実施予定。", scheduled_date: Date.new(2026, 4, 1), status: "planned")
maintenances[:m17] = ScheduledMaintenance.create!(equipment: sk_crf2, title: "堺CRF 計器年次点検", description: "堺接触改質装置計器の年次点検。反応器温度・圧力計器を中心に校正実施。", scheduled_date: Date.new(2026, 4, 10), status: "planned")
maintenances[:m18] = ScheduledMaintenance.create!(equipment: wk_fcc3, title: "和歌山FCC 計器定期整備", description: "和歌山FCC装置計器定期整備。反応塔・再生塔温度計一斉校正。", scheduled_date: Date.new(2026, 5, 1), status: "planned")
maintenances[:m19] = ScheduledMaintenance.create!(equipment: sk_tank, title: "堺タンクヤード 計器年次点検", description: "堺タンクヤードの液位計・温度計年次点検。レーダーレベル計のアンテナ清掃含む。", scheduled_date: Date.new(2026, 3, 20), status: "planned")
maintenances[:m20] = ScheduledMaintenance.create!(equipment: ng_tank, title: "根岸タンクヤード 液位計点検", description: "根岸タンクヤード液位計定期点検。", scheduled_date: Date.new(2026, 4, 5), status: "planned")
maintenances[:m21] = ScheduledMaintenance.create!(equipment: sd_tank, title: "仙台タンクヤード 計器点検", description: "仙台タンクヤード全計器の定期点検。レーダーレベル計校正含む。", scheduled_date: Date.new(2026, 3, 10), status: "planned")
maintenances[:m22] = ScheduledMaintenance.create!(equipment: kw_rhds3, title: "RHDS 高圧計器定期整備", description: "RHDS高圧系計器定期整備。水素系高圧伝送器の定期校正。防爆仕様装置のため協力会社立会のもと実施。", scheduled_date: Date.new(2026, 5, 15), status: "planned")
maintenances[:m23] = ScheduledMaintenance.create!(equipment: equip("堺製油所", "常圧蒸留装置"), title: "堺CDU 前回年次点検", description: "前回の年次点検整備。完了済み。", scheduled_date: Date.new(2025, 4, 5), completed_date: Date.new(2025, 4, 8), status: "completed", used_materials: "差圧伝送器EJA110E × 1台、ガスケット × 8枚")
maintenances[:m24] = ScheduledMaintenance.create!(equipment: equip("和歌山製油所", "常圧蒸留装置"), title: "和歌山CDU 安全弁検査", description: "和歌山CDU安全弁法定検査。前回検査から2年経過。", scheduled_date: Date.new(2025, 10, 15), completed_date: Date.new(2025, 10, 17), status: "completed")
maintenances[:m25] = ScheduledMaintenance.create!(equipment: equip("仙台製油所", "潤滑油製造装置"), title: "仙台LK 前回年次点検", description: "前回の年次点検整備。完了済み。", scheduled_date: Date.new(2025, 3, 5), completed_date: Date.new(2025, 3, 8), status: "completed", used_materials: "温度伝送器YTA510 × 1台、ガスケット × 6枚")

honda_ng     = user_by("honda_ng@example.com")
wk_inst_mgr2 = user_by("kawamoto@example.com")
doi2         = user_by("doi@example.com")

MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m16], user: suzuki, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m16], user: sato, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m16], user: yoshida, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m17], user: kimura, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m17], user: hayashi, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m18], user: wk_inst_mgr2, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m18], user: doi2, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m19], user: kimura, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m20], user: yamashita, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m20], user: honda_ng, role: "member")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m21], user: sd_inst1, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m22], user: suzuki, role: "lead")
MaintenanceAssignment.create!(scheduled_maintenance: maintenances[:m22], user: inoue, role: "member")
